name: Bug report
description: File a bug report
title: "[Bug]: "
labels: [bug]

body:
    - type: markdown
      attributes:
        value: |
          Thanks for taking the time to file a bug report. Provide as much information as possible to help dev identify and solve the problem.

    - type: dropdown
      id: install_method
      attributes:
        label: Install method
        description: Which install method did you use?
        options:
          - Linux executable
          - MacOS app
          - Windows extract
          - Windows installer
          - Running from source
          - Third party (AUR, Docker, Chocolatey, etc. Specify in comments)
      validations:
        required: true

    - type: dropdown
      id: os
      attributes:
        label: Operating system
        description: What operating system do you use?
        options:
          - Windows 10
          - Windows 11
          - Windows, older. (Specify in comments)
          - MacOS 11 "Big Sur" x86
          - MacOS 11 "Big Sur" ARM
          - MacOS 10.15 "Catalina"
          - MacOS, older (Specify in comments)
          - Linux (Specify distro and version in comments)
      validations:
        required: true